### ISSUE TITLE
Fadein

### ISSUE THREAD

**Issue by woutervanwijk** [CHRISTOPANANJICKAL/fast_cached_network_image#1]
Very nice package! The only thing that you could maybe add, is a way to easily fadein the image?

**Comment by CHRISTOPANANJICKAL** [comment]
Definitely, this feature will be coming soon in the next update

**Comment by CHRISTOPANANJICKAL** [comment]
@woutervanwijk  This feature is now added in v0.0.4.

**Comment by woutervanwijk** [comment]
You're fast! Thx
