### ISSUE TITLE
这个插件和cached_network_image的区别是什么？

### ISSUE THREAD

**Issue by wengxianxun** [CHRISTOPANANJICKAL/fast_cached_network_image#12]
这个插件和cached_network_image的区别是什么？

**Comment by christoPBG** [comment]
cached_network_image uses SQL where as fast_cached_network_image uses Hive. fast_cached_network_image is written in pure dart and supports all 6 platforms in a flutter. It also provides methods to check whether an image is cached or not, methods to clear the cache, and methods to remove a specific image from the cache, and much more.
