### ISSUE TITLE
XMLHttpRequest error

### ISSUE THREAD

**Issue by anmol-me** [CHRISTOPANANJICKAL/fast_cached_network_image#19]
Getting error with fetching-
https://api.time.com/wp-content/uploads/2023/04/florida-flooding-04.jpg

![fast_image_xml_error](https://user-images.githubusercontent.com/39460326/232298739-510eba66-d825-4d26-8a1b-55de1ccfd3e7.JPG)

**Comment by CHRISTOPANANJICKAL** [comment]
![image](https://user-images.githubusercontent.com/58786637/233857179-c127943c-c3ad-4ce7-b72b-2b315a6e52d5.png)

**Comment by NeroThroN** [comment]
Same error as @anmol-me

When I replace `Image.network` by `FastCachedImage`, all my images didn't load on web and throws XMLHttpRequest errors.

@CHRISTOPANANJICKAL can you try your example but on a chrome device ?

**Comment by CHRISTOPANANJICKAL** [comment]
You can fix the CORS issue in your server-side or you can use a proxy.
