### ISSUE TITLE
repeat property doesn't work on animated webp images

### ISSUE THREAD

**Issue by ChristopheChanteur** [CHRISTOPANANJICKAL/fast_cached_network_image#21]
Hi, 
Thank you for this great package.
the repeat property seems to have no effect on animated webp images - it keeps on looping the animation for either option of this property.

**Comment by CHRISTOPANANJICKAL** [comment]
The repeat property is directly passed to Image.memory widget from flutter. Please make sure your idea is working with Image.memory.
