### ISSUE TITLE
404 on Flutter Web

### ISSUE THREAD

**Issue by evertonfoz** [CHRISTOPANANJICKAL/fast_cached_network_image#22]
Hello. All good? 

I'm using it at startup (Flutter Web): 

`await FastCachedImageConfig.init(clearCacheAfter: const Duration(days: 7));`

 and then 
 
 ```
FastCachedImage(
                           url:
                               kHandWithCellphoneWithoutContentWithPhotoTransparentBackground,
                           fit: BoxFit.cover,
                           scale: lpHomeViewModel.handScale,
                           fadeInDuration: const Duration(seconds: 1),
                           errorBuilder: (context, exception, stacktrace) {
                             return Text(stacktrace.toString());
                           },
                           loadingBuilder: (context, progress) {
                             debugPrint(
                               'Progress: ${progress.isDownloading} ${progress.downloadedBytes} / ${progress.totalBytes}',
                             );
                             return Stack(
                               alignment: Alignment.center,
                               children: [
                                 if (progress.isDownloading &&
                                     progress.totalBytes != null)
                                   Text(
                                     '${progress.downloadedBytes ~/ 1024} / ${progress.totalBytes! ~/ 1024} kb',
                                     style: const TextStyle(color: Colors.red),
                                   ),
                                 SizedBox(
                                   width: 120,
                                   height: 120,
                                   child: CircularProgressIndicator(
                                     color: Colors.red,
                                     value: progress.progressPercentage.value,
                                   ),
                                 ),
                               ],
                             );
                           },
                         ),
```

When I run it locally, it works, when I use it in production I get a 404 for 'assets/images/landing_page/mao_com_celular_sem_conteudo_com_foto_transparente.png';

Can you help me?

**Comment by harshhhh15** [comment]
It's possible that the file 'mao_com_celular_sem_conteudo_com_foto_transparente.png' is not properly included in your production build. Here are a few steps you can take to troubleshoot the issue:

1. Check if the file is included in the asset section of your pubspec.yaml file. Make sure it is spelled correctly and the file path is correct.

2. Run the command `flutter clean` to clear any previously built files and then rebuild your project using the command `flutter build web --release`.

3. Check the built files to see if the image file is included in the assets folder. You can find the built files in the `build/web` folder of your project.

4. If the file is still not included, try manually copying the file to the assets folder in the built files and then rebuilding your project.

5. If none of the above steps work, try changing the URL to the image file to an absolute URL and see if that works.
