### ISSUE TITLE
File header was empty.

### ISSUE THREAD

**Issue by mingxin-yang** [CHRISTOPANANJICKAL/fast_cached_network_image#24]
ImageCodecException: Failed to detect image file format using the file header.
File header was empty.
Image source: encoded image bytes - Image url : https://oaidalleapiprodscus.blob.core.windows.net/private/org-DwYbEOmWxxN0LNW5OhlgXlGb/user-9PstBVHFvUMoUQzsGXqpum4Y/img-rfE88GJ3nco2JcyzA3ngt1AP.png?st=2023-05-24T16%3A08%3A02Z&se=2023-05-24T18%3A08%3A02Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-05-24T00%3A13%3A23Z&ske=2023-05-25T00%3A13%3A23Z&sks=b&skv=2021-08-06&sig=63Wh5fEUBdkZcLTOjq78RIfGNIWUQUvnApzZm6JHtek%3D

**Comment by maliatli** [comment]
I'm having the same problem.

**Comment by hkrwhitehat** [comment]
I think this is a CORS issue.

**Comment by CHRISTOPANANJICKAL** [comment]
Seems this issue is not related to the package
