### ISSUE TITLE
Feature request: Image Builder

### ISSUE THREAD

**Issue by SasLuca** [CHRISTOPANANJICKAL/fast_cached_network_image#25]
I think it would be useful to have an optional `imageBuilder` to go alongside `loadingBuilder` and `errorBuilder`.

I came up with the need for this when trying to add an `InkWell` effect to an image.
I either had to do use `Ink.image` with `FastCachedImageProvider` and give up on `loadingBuilder` and `errorBuilder` or use a `Stack` to have the inkwell effect on top of the image.

While the latter solution works, an `imageBuilder` would have allowed me to simply use an `Ink.image` while keeping the useful `loadingBuilder` and `errorBuilder` functionality.

**Comment by CHRISTOPANANJICKAL** [comment]
Image builder cannot be added since the package itself is making use of the frameBuillder property in memmory.image from flutter framework
