### ISSUE TITLE
how do I add curve edges using this plugins? 

### ISSUE THREAD

**Issue by frendcarlo** [CHRISTOPANANJICKAL/fast_cached_network_image#32]
`SizedBox(
            height: 300,
            width: double.maxFinite,
            child: FastCachedImage(
              url: eventItemData.imageUrl!,
              fit: BoxFit.fitWidth,
              fadeInDuration: const Duration(seconds: 1),
            ),
          ),`

tried this 

`Container(
                    height: 200,
                    width: double.infinity,
                    decoration: BoxDecoration(
    color: Colors.transparent,
    border: Border.all(
      color: Colors.grey.withOpacity(0.02),
      width: 0.5,
    ),
    boxShadow: [
      BoxShadow(
        color: Colors.black.withOpacity(0.03),
        spreadRadius: 5,
        blurRadius: 7,
        offset: const Offset(0, 2),
      ),
    ],
    borderRadius: BorderRadius.circular(5.0),
  ), 
child: FastCachedImage(
              url: eventItemData.imageUrl!,
              fit: BoxFit.fitWidth,
              fadeInDuration: const Duration(seconds: 1),
            ),
 ),`

but seems like it doesn't give me curve edges.

**Comment by CHRISTOPANANJICKAL** [comment]
Did you try using cliprrect widget?

**Comment by frendcarlo** [comment]
that indeed solve the problem. thanks
