### ISSUE TITLE
Lock when running two app

### ISSUE THREAD

**Issue by divan** [CHRISTOPANANJICKAL/fast_cached_network_image#34]
I'm running same flutter app that uses `fast_cached_network_image` twice (as MacOS build), because I need two instances of the app to test some functionality. However, second instance run has failed with an exception

```
Unhandled Exception: FileSystemException: lock failed, path = '/Users/.../Library/Containers/.../Data/Documents/cachedimages.lock' (OS Error: Resource temporarily unavailable, errno = 35)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1022:7)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81:5)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160:12)
<asynchronous suspension>
#5      FastCachedImageConfig.init (package:fast_cached_network_image/src/fast_cached_image.dart:372:17)
<asynchronous suspension>
#6      main (package:.../main.dart:38:3)
<asynchronous suspension>
```

I see there is an option to provide custom subDir to `.init()`, but maybe initialization should be more permisive, and, let's say, use second instance in a read-only mode? Basically the default usage example in Readme makes second application unusable (black screen on startup).

**Comment by christoPBG** [comment]
@divan you must not create two instances of the package. The FastCachedNewtoekImage.init() function must be called only once in the app.
