### ISSUE TITLE
image state issue

### ISSUE THREAD

**Issue by Waqas027** [CHRISTOPANANJICKAL/fast_cached_network_image#38]
Hey I load list of image in a listview and I used this package. When I do searching so it does not change the image it shows the same images. like I search an item in a list so it will filter out the list and it will show only those items which matches the search term so I see the title which match the search but it shows wrong image for this item. can u help

**Comment by Waqas027** [comment]
here is the code 

class ImagesCategoryScreen extends StatefulWidget {
  const ImagesCategoryScreen({Key? key}) : super(key: key);

  @override
  State<ImagesCategoryScreen> createState() => _ImagesCategoryScreenState();
}

class _ImagesCategoryScreenState extends State<ImagesCategoryScreen> {
  TextEditingController controller = TextEditingController();
  String searchQuery = "";
  bool isSearching = false;
  String title = "Images";

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    int network = Provider.of<int>(context);
    List arguments = ModalRoute.of(context)!.settings.arguments! as List;
    title = arguments[1];
    List<Category> categories = (arguments[0] as List<Category>).where((category) {
      return category.title!.toLowerCase().contains(searchQuery.toLowerCase());
    }).toList();

    return Scaffold(
      appBar: AppBar(
        iconTheme: const IconThemeData(color: Colors.white),
        leading: IconButton(onPressed: (){
          if(!isSearching){
            Navigator.of(context).pop();
          }else{
            resetState();
          }
        }, icon: const Icon(Icons.arrow_back)),
        title: isSearching ? CustomSearchBarWidget(
          controller: controller,
          onChange: (value){
            setState(() {
              searchQuery = value;
            });
          },) : Text(title,style: const TextStyle(color: Colors.white),),
        backgroundColor: appBarColor,
        actions: [
          isSearching ? IconButton(onPressed: (){
            resetState();
          }, icon: const Icon(Icons.close)) : const SizedBox.shrink(),
          !isSearching ? IconButton(onPressed: (){
            setState(() {
              isSearching = true;
            });
          }, icon: const Icon(Icons.search)): const SizedBox.shrink()],
      ),
      body: ListView.builder(
        itemCount: categories.length,
        itemBuilder: (context, index) {
          Category category = categories[index];
          print(category.thumbnail);
          return _buildItem(
              category.title!,
              category.thumbnail,
              onTap: () {
                resetState();
                var provider = Provider.of<ImagesDataProvider>(context,listen: false);
                provider.setSelectedCategory(category.title!);
                if(category.children != null){
                  if(category.children!.isNotEmpty){
                    Navigator.of(context).pushNamed(AppRoutes.imagesCategories,arguments: [category.children!,category.title]);
                  }else{
                    if(network == 1){
                      provider.getFiles(context: context,categoryId: category.id);
                    }else{
                      if(provider.allFileList.isNotEmpty){
                        provider.gotoFilesScreen(context, category.id.toString());
                      }else{
                        showSomeMsg("No Items Found! Internet is Required to fetch New Items", context);
                      }
                    }
                  }
                }else{
                  if(network == 1){
                    provider.getFiles(context: context,categoryId: category.id);
                  }else{
                    if(provider.allFileList.isNotEmpty){
                      provider.gotoFilesScreen(context, category.id.toString());
                    }else{
                      showSomeMsg("No Items Found! Internet is Required to fetch New Items", context);
                    }
                  }
                }
              }
          );
        },
      ),
    );
  }

  resetState(){
    controller.text = "";
    setState(() {
      searchQuery = "";
      isSearching = false;
    });
  }

  _buildItem(String title,String? imagePath,{required VoidCallback onTap}){
    return Container(
      margin: const EdgeInsets.all(10),
      child: InkWell(
        onTap: onTap,
        child: buildDecoratedContainer(
            Row(
              children: [
                imagePath != null ? ClipRRect(
                  borderRadius: BorderRadius.circular(15.r),
                  child:
                  SizedBox(
                    height:150.h,width: 100.w,
                    child: FastCachedImage(
                      url: "$thumbnailBaseUrl/$imagePath",
                      fit: BoxFit.cover,
                      fadeInDuration: Duration.zero,
                      cacheWidth: 200,
                      errorBuilder: (context, exception, stacktrace) {
                        return Center(child: Icon(Icons.error));
                      },
                      loadingBuilder: (context, progress) {
                        return Center(child: CircularProgressIndicator(color: Colors.red, value: progress.progressPercentage.value));
                      },
                    )
                  )
                ):const Icon(
                    Icons.image
                ),
                SizedBox(width: 10.w,),
                Text(title,style: TextStyle(fontSize: 20.sp,fontWeight: FontWeight.w600,),)
              ],
            ),h: 100.h,w: 100.w
        ),
      ),
    );
  }
}

**Comment by CHRISTOPANANJICKAL** [comment]
Please try adding a key to the list tile widget widget which you use. Closing this issue because I don't think this is an issue related to the package.
