### ISSUE TITLE
Add support multi instance!

### ISSUE THREAD

**Issue by ShafiqSadat** [CHRISTOPANANJICKAL/fast_cached_network_image#39]
currently its not supported and has an error:

'C:\Users\PC\Documents\cachedimageskeys.lock' (OS Error: The process cannot access the file because another process has locked a portion of the file.

**Comment by CHRISTOPANANJICKAL** [comment]
#34  closing as mentioned here.

**Comment by christoPBG** [comment]
Please use different cache paths for different applications
