### ISSUE TITLE
loadingBuilder required in package 1.0.1

### ISSUE THREAD

**Issue by large** [CHRISTOPANANJICKAL/fast_cached_network_image#4]
I have just upgraded to latest version and I had some issues.
Images that did not use the loadingBuilder failed, with this error:
`flutter: Null check operator used on a null value - Image url : <link to image>`

After adding `loadingBuilder: (c, p) { return Container(); }` everything was back to normal.
If these functions are an requirement, they should not be optional.

**Comment by CHRISTOPANANJICKAL** [comment]
Thanks for the report @large .I will check and update

**Comment by CHRISTOPANANJICKAL** [comment]
Loading builder is optional now.
