### ISSUE TITLE
Why don't you use cacheWidth and cacheHeight in your code

### ISSUE THREAD

**Issue by wumeixinjiazu** [CHRISTOPANANJICKAL/fast_cached_network_image#41]
<img width="488" alt="image" src="https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image/assets/36200075/2d060922-61a8-4c1b-97ca-3c2c97e3a0f5">

**Comment by BenSathyanATeam** [comment]
Thats probably a mistake. We can fix this in the next update

**Comment by CHRISTOPANANJICKAL** [comment]
That's probably a mistake and can be fixed in the next update. Thanks @wumeixinjiazu for notifying.

**Comment by CHRISTOPANANJICKAL** [comment]
Fixed
