### ISSUE TITLE
uuid version is not up to date

### ISSUE THREAD

**Issue by 9d77v** [CHRISTOPANANJICKAL/fast_cached_network_image#43]
Because fast_cached_network_image 1.2.0 depends on uuid ^3.0.7 and no versions of fast_cached_network_image match >1.2.0 <2.0.0, fast_cached_network_image ^1.2.0 requires uuid ^3.0.7.
So, because xxx depends on both fast_cached_network_image ^1.2.0 and uuid ^4.0.3, version solving failed.

**Comment by CHRISTOPANANJICKAL** [comment]
Version updated
