### ISSUE TITLE
Flutter Web Canvaskit Renderer issue!

### ISSUE THREAD

**Issue by migdev-br** [CHRISTOPANANJICKAL/fast_cached_network_image#45]
Hi team, I am getting the following error once I build Flutter web as renderer canvaskit.

"File header was [0x3c 0x21 0x44 0x4f 0x43 0x54 0x59 0x50 0x45 0x20].
Image source: encoded image bytes - Image url : 
Another exception was thrown: Image MemoryImage(Uint8List#41c52)"

pls have a look,
thx in advance

**Comment by CHRISTOPANANJICKAL** [comment]
is the image url empty?

**Comment by migdev-br** [comment]
Sorry, the issue was on my end, it's working perfectly!
