### ISSUE TITLE
Difference w/ cached_network_image

### ISSUE THREAD

**Issue by dhikshith12** [CHRISTOPANANJICKAL/fast_cached_network_image#54]
Hello devs, i'm trying to migrate from [cached_network_image](https://pub.dev/packages/cached_network_image) to this package, so i got curious what makes this faster..? 

did you have any problem with that package that motivated you to develop this?

also is the API Interface similar to the cached_network_image..?

**Comment by CHRISTOPANANJICKAL** [comment]
This package uses hive DB which is much faster than SQL DB (which CNI uses). This package supports all 6 platforms of flutter where as CNI supports 3 platforms. This package provides function to delete a canced image, set cache clearing date and many other functions.

**Comment by escamoteur** [comment]
do you have any benchmarks that show how big the difference to CNI is?
