### ISSUE TITLE
Reload widget when change URL

### ISSUE THREAD

**Issue by marcoprodata** [CHRISTOPANANJICKAL/fast_cached_network_image#6]
Dear friend, when change the url the widget dont update the image.

Observer(
  builder: (_) {
    return SizedBox(
      height: double.maxFinite,
      child: RotatedBox(
        quarterTurns: _rotate,
        child: FastCachedImage(
          url: premio.urlCanhoto,
          fit: BoxFit.fill,
          fadeInDuration: const Duration(seconds: 1),
          errorBuilder: (context, exception, stacktrace) {
            return Text(stacktrace.toString());
          },
          loadingBuilder: (context, progress) {
            return Container();
          },
        ),
      ),
    );
  },
)

How to change URL and update the widget?

Thanks to advance

**Comment by CHRISTOPANANJICKAL** [comment]
Hii @marcoprodata, can you please explain in detail?

**Comment by marcoprodata** [comment]
Dear Friend, here's the thing, I have an object on the screen, and a list of items next to it, with each item I click I intend to change the image displayed on the widget, the url of the image is in a store, so when updating I expected the image was updated on the widget, but it doesn't

**Comment by CHRISTOPANANJICKAL** [comment]
Can you share the full piece of code so that i can look jnto tue issue

**Comment by yzq666** [comment]
![image](https://user-images.githubusercontent.com/24952360/206980604-ccfb7a1c-a5ba-4aaa-a67a-5aad870d0f74.png)
Because the key is not updated, Imagecache not change,

**Comment by WiRight** [comment]
Maybe it will be much better solution for you?

```dart
await FastCachedImageConfig.deleteCachedImage(
      imageUrl: url,
);
```

**Comment by CHRISTOPANANJICKAL** [comment]
https://user-images.githubusercontent.com/58786637/233856487-8757d78e-55b2-46e8-8366-75c101103622.mp4

For images with different url using Key param will work. For images with the same url, you will have to delete the cached image first and then call the widget again. but somehow you need to identify whether the images are the same or different
